# Generated by Django 4.1.3 on 2023-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontenjan", "0002_hemsire_alter_ebe_kodu_alter_ebe_kurumadı_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="s2021",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tip", models.CharField(max_length=100)),
                ("kodu", models.CharField(max_length=10)),
                ("sbkodu", models.CharField(max_length=7)),
                ("kurumadı", models.CharField(max_length=70)),
                ("sehir", models.CharField(max_length=17)),
                ("sayi", models.CharField(max_length=17)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
