# Generated by Django 4.1.3 on 2023-03-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontenjan", "0003_s2021"),
    ]

    operations = [
        migrations.AddField(
            model_name="s2021",
            name="punvani",
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
